name: yumma
description: Root wrapper package for the Yumma Flutter monorepo.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  food_delivery_customer:
    path: customer

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
