org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=4
org.gradle.caching=true
android.useAndroidX=true
kotlin.incremental=true
GOOGLE_MAPS_API_KEY=AIzaSyAne1dRhUXBFZ-U0lK3vXGb93RKLSkyhTc
API_BASE_URL=https://yumma.online/api
SUPPORT_PHONE=+919279380225
SUPPORT_EMAIL=info@yumma.online
